# Generated by Django 5.2.7 on 2025-12-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControleDeRecebimentos', '0002_empreendimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
