# Generated by Django 5.2.7 on 2025-12-22 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControleDeRecebimentos', '0003_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_venda', models.DateField()),
                ('mes_referencia', models.CharField(max_length=7)),
                ('forma_pagamento', models.CharField(choices=[('AV', 'À Vista'), ('FI', 'Financiado')], max_length=2)),
                ('status', models.CharField(choices=[('PE', 'Pendente'), ('FA', 'Faturado')], default='PE', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControleDeRecebimentos.cliente')),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControleDeRecebimentos.empreendimento')),
            ],
        ),
    ]
