# Generated by Django 5.2.7 on 2025-12-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControleDeRecebimentos', '0005_venda_corretor_venda_etapa_venda_fgts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.CharField(max_length=7, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
