# Generated by Django 5.2.7 on 2025-12-23 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControleDeRecebimentos', '0006_tabelamensal'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='venda',
            unique_together={('cliente', 'empreendimento', 'unidade', 'data_venda')},
        ),
        migrations.AddField(
            model_name='venda',
            name='tabela_mensal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='ControleDeRecebimentos.tabelamensal'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='venda',
            name='mes_referencia',
        ),
    ]
