# Generated by Django 5.2.7 on 2025-12-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControleDeRecebimentos', '0007_alter_venda_unique_together_venda_tabela_mensal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='data_faturamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='valor_comissao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
