# Generated by Django 5.2.7 on 2025-12-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControleDeRecebimentos', '0008_venda_data_faturamento_venda_valor_comissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('AV', 'À Vista'), ('FI', 'Financiado'), ('DS', 'Desconto')], max_length=2, null=True),
        ),
    ]
