# Generated by Django 5.2.7 on 2025-12-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControleDeRecebimentos', '0009_alter_venda_forma_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseEPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PE', 'Pendente'), ('CO', 'Confirmado'), ('CA', 'Cancelado')], default='PE', max_length=2)),
                ('confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('vendas_ids', models.JSONField(default=list)),
                ('dados_epr', models.JSONField(default=list)),
                ('total_encontradas', models.IntegerField(default=0)),
                ('resumo_por_mes', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Análise EPR',
                'verbose_name_plural': 'Análises EPR',
                'ordering': ['-created_at'],
            },
        ),
    ]
