# Generated by Django 5.2.7 on 2025-12-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControleDeRecebimentos', '0010_analise_epr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('PE', 'Pendente'), ('FA', 'Faturado'), ('CA', 'Cancelado')], default='PE', max_length=2),
        ),
    ]
